package com.example.daggerexample;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import com.example.daggerexample.di.CarComponent;
import com.example.daggerexample.di.DaggerCarComponent;
import com.example.daggerexample.di.ElectricEngineModule;
import com.example.daggerexample.model.Car;

import javax.inject.Inject;

public class MainActivity extends AppCompatActivity {

    /**
     * Field Injection
     * */
    @Inject
    Car car;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        /**
         * Returns the implementation of CarComponent interface, which is generated by Dagger.
         * */
        CarComponent carComponent = DaggerCarComponent.builder()
                .withPower(500)
                .withEngineCapacity(1500)
                .build();

        /**
         * Calling Inject method is important for car field injection, with the reference of class/activity
         *
         * Note: Here we could not initialize car instance using constructor injection as we directly does
         * not call constructor of MainActivity, as it is called by Android System.
         * */
        carComponent.inject(this);

        car.drive();
    }
}